name: Deploy Project to App Engine

on:
  push:
    branches:
      - main

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:

# [KADEN] CHANGED for tmp deployment
#  test:
#    name: Test and Sonarqube
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository code
#        uses: actions/checkout@v3 # [KADEN] EDITTED for the issue 'Node.js 12 actions are deprecated.'
#
#      - name: Install Java 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: "temurin"
#          java-version: "17"
#
#      - name: Test and analyze
#        run: ./gradlew test jacocoTestReport sonarqube
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
#    needs: test # [KADEN] CHANGED for tmp deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # [KADEN] EDITTED for the issue 'Node.js 12 actions are deprecated.'

      # [KADEN] NEWLY ADDED FOR Github Secret Key---------------------------------
      # Github Secret Key should be string e.g. "<<secret key>>", not just <<secret key>>
      - name: Generate env file with using github secrets
        id: generate_dotenv_file
        env:
          INVISIBLE_KEY: ${{ secrets.INVISIBLE_KEY }}
          GCP_SERVICE_CREDENTIALS: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
        run: echo "INVISIBLE_KEY=$INVISIBLE_KEY" > forappyaml.env

      - name: Prepare app.yaml
        id: prepare-app-yaml
        uses: mshick/fast-envsubst@v1
        with:
          env-file: forappyaml.env
          in-file: app.yaml.template
          out-file: app.yaml
      # -------------------------------------------------------------------

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v2 # [KADEN] CHANGED for websocket from v1 to v2
          # credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}  # [KADEN] CHANGED for tmp deployment
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS_TMP }}
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
